---
version: "2.1"
services:
  lavalink:
    image: zingytomato/lavalink
    container_name: lavalink
    environment: 
      - PASSWORD=PASSWORD 
    ports:
      - 2333:2333 # External port can be changed
    restart: unless-stopped
