---
version: "2.1"
services:
  lavalink:
    image: zingytomato/lavalink
    container_name: lavalink
    environment: 
      - PASSWORD= "password"
    ports:
      - 2333:2333
    restart: unless-stopped
